name: Tests
on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  build_and_test:
    name: "Testing application"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run test